//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string IsEnable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Publisher { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.Guid> Classification { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Price { get; set; }
        public string Language { get; set; }
        public string Binding { get; set; }
        public string Class { get; set; }
        public string SubClass { get; set; }
    }
}
